# coding: utf-8

"""
    Huidige bevragingen API

    Deze API levert actuele gegevens over adressen, adresseerbaar objecten en panden. Actueel betekent in deze API `zonder eindstatus`. De bron voor deze API is de basisregistratie adressen en gebouwen (BAG).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: bag@kadaster.nl
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class AdresLinks(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        '_self': 'HalLink',
        'openbare_ruimte': 'HalLink',
        'nummeraanduiding': 'HalLink',
        'woonplaats': 'HalLink',
        'adresseerbaar_object': 'HalLink',
        'panden': 'list[HalLink]'
    }

    attribute_map = {
        '_self': 'self',
        'openbare_ruimte': 'openbareRuimte',
        'nummeraanduiding': 'nummeraanduiding',
        'woonplaats': 'woonplaats',
        'adresseerbaar_object': 'adresseerbaarObject',
        'panden': 'panden'
    }

    def __init__(self, _self=None, openbare_ruimte=None, nummeraanduiding=None, woonplaats=None, adresseerbaar_object=None, panden=None, local_vars_configuration=None):  # noqa: E501
        """AdresLinks - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self.__self = None
        self._openbare_ruimte = None
        self._nummeraanduiding = None
        self._woonplaats = None
        self._adresseerbaar_object = None
        self._panden = None
        self.discriminator = None

        if _self is not None:
            self._self = _self
        if openbare_ruimte is not None:
            self.openbare_ruimte = openbare_ruimte
        if nummeraanduiding is not None:
            self.nummeraanduiding = nummeraanduiding
        if woonplaats is not None:
            self.woonplaats = woonplaats
        if adresseerbaar_object is not None:
            self.adresseerbaar_object = adresseerbaar_object
        if panden is not None:
            self.panden = panden

    @property
    def _self(self):
        """Gets the _self of this AdresLinks.  # noqa: E501


        :return: The _self of this AdresLinks.  # noqa: E501
        :rtype: HalLink
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this AdresLinks.


        :param _self: The _self of this AdresLinks.  # noqa: E501
        :type: HalLink
        """

        self.__self = _self

    @property
    def openbare_ruimte(self):
        """Gets the openbare_ruimte of this AdresLinks.  # noqa: E501


        :return: The openbare_ruimte of this AdresLinks.  # noqa: E501
        :rtype: HalLink
        """
        return self._openbare_ruimte

    @openbare_ruimte.setter
    def openbare_ruimte(self, openbare_ruimte):
        """Sets the openbare_ruimte of this AdresLinks.


        :param openbare_ruimte: The openbare_ruimte of this AdresLinks.  # noqa: E501
        :type: HalLink
        """

        self._openbare_ruimte = openbare_ruimte

    @property
    def nummeraanduiding(self):
        """Gets the nummeraanduiding of this AdresLinks.  # noqa: E501


        :return: The nummeraanduiding of this AdresLinks.  # noqa: E501
        :rtype: HalLink
        """
        return self._nummeraanduiding

    @nummeraanduiding.setter
    def nummeraanduiding(self, nummeraanduiding):
        """Sets the nummeraanduiding of this AdresLinks.


        :param nummeraanduiding: The nummeraanduiding of this AdresLinks.  # noqa: E501
        :type: HalLink
        """

        self._nummeraanduiding = nummeraanduiding

    @property
    def woonplaats(self):
        """Gets the woonplaats of this AdresLinks.  # noqa: E501


        :return: The woonplaats of this AdresLinks.  # noqa: E501
        :rtype: HalLink
        """
        return self._woonplaats

    @woonplaats.setter
    def woonplaats(self, woonplaats):
        """Sets the woonplaats of this AdresLinks.


        :param woonplaats: The woonplaats of this AdresLinks.  # noqa: E501
        :type: HalLink
        """

        self._woonplaats = woonplaats

    @property
    def adresseerbaar_object(self):
        """Gets the adresseerbaar_object of this AdresLinks.  # noqa: E501


        :return: The adresseerbaar_object of this AdresLinks.  # noqa: E501
        :rtype: HalLink
        """
        return self._adresseerbaar_object

    @adresseerbaar_object.setter
    def adresseerbaar_object(self, adresseerbaar_object):
        """Sets the adresseerbaar_object of this AdresLinks.


        :param adresseerbaar_object: The adresseerbaar_object of this AdresLinks.  # noqa: E501
        :type: HalLink
        """

        self._adresseerbaar_object = adresseerbaar_object

    @property
    def panden(self):
        """Gets the panden of this AdresLinks.  # noqa: E501

        Het/de aan het adres gerelateerde pand(en).  # noqa: E501

        :return: The panden of this AdresLinks.  # noqa: E501
        :rtype: list[HalLink]
        """
        return self._panden

    @panden.setter
    def panden(self, panden):
        """Sets the panden of this AdresLinks.

        Het/de aan het adres gerelateerde pand(en).  # noqa: E501

        :param panden: The panden of this AdresLinks.  # noqa: E501
        :type: list[HalLink]
        """

        self._panden = panden

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdresLinks):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AdresLinks):
            return True

        return self.to_dict() != other.to_dict()
