# coding: utf-8

"""
    Huidige bevragingen API

    Deze API levert actuele gegevens over adressen, adresseerbaar objecten en panden. Actueel betekent in deze API `zonder eindstatus`. De bron voor deze API is de basisregistratie adressen en gebouwen (BAG).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: bag@kadaster.nl
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class AdresMogelijkOnjuist(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'korte_naam': 'bool',
        'straat': 'bool',
        'huisnummer': 'bool',
        'huisletter': 'bool',
        'huisnummertoevoeging': 'bool',
        'postcode': 'bool',
        'woonplaats': 'bool',
        'nummeraanduiding_identificatie': 'bool',
        'openbare_ruimte_identificatie': 'bool',
        'woonplaats_identificatie': 'bool',
        'toelichting': 'list[str]'
    }

    attribute_map = {
        'korte_naam': 'korteNaam',
        'straat': 'straat',
        'huisnummer': 'huisnummer',
        'huisletter': 'huisletter',
        'huisnummertoevoeging': 'huisnummertoevoeging',
        'postcode': 'postcode',
        'woonplaats': 'woonplaats',
        'nummeraanduiding_identificatie': 'nummeraanduidingIdentificatie',
        'openbare_ruimte_identificatie': 'openbareRuimteIdentificatie',
        'woonplaats_identificatie': 'woonplaatsIdentificatie',
        'toelichting': 'toelichting'
    }

    def __init__(self, korte_naam=None, straat=None, huisnummer=None, huisletter=None, huisnummertoevoeging=None, postcode=None, woonplaats=None, nummeraanduiding_identificatie=None, openbare_ruimte_identificatie=None, woonplaats_identificatie=None, toelichting=None, local_vars_configuration=None):  # noqa: E501
        """AdresMogelijkOnjuist - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._korte_naam = None
        self._straat = None
        self._huisnummer = None
        self._huisletter = None
        self._huisnummertoevoeging = None
        self._postcode = None
        self._woonplaats = None
        self._nummeraanduiding_identificatie = None
        self._openbare_ruimte_identificatie = None
        self._woonplaats_identificatie = None
        self._toelichting = None
        self.discriminator = None

        if korte_naam is not None:
            self.korte_naam = korte_naam
        if straat is not None:
            self.straat = straat
        if huisnummer is not None:
            self.huisnummer = huisnummer
        if huisletter is not None:
            self.huisletter = huisletter
        if huisnummertoevoeging is not None:
            self.huisnummertoevoeging = huisnummertoevoeging
        if postcode is not None:
            self.postcode = postcode
        if woonplaats is not None:
            self.woonplaats = woonplaats
        if nummeraanduiding_identificatie is not None:
            self.nummeraanduiding_identificatie = nummeraanduiding_identificatie
        if openbare_ruimte_identificatie is not None:
            self.openbare_ruimte_identificatie = openbare_ruimte_identificatie
        if woonplaats_identificatie is not None:
            self.woonplaats_identificatie = woonplaats_identificatie
        if toelichting is not None:
            self.toelichting = toelichting

    @property
    def korte_naam(self):
        """Gets the korte_naam of this AdresMogelijkOnjuist.  # noqa: E501


        :return: The korte_naam of this AdresMogelijkOnjuist.  # noqa: E501
        :rtype: bool
        """
        return self._korte_naam

    @korte_naam.setter
    def korte_naam(self, korte_naam):
        """Sets the korte_naam of this AdresMogelijkOnjuist.


        :param korte_naam: The korte_naam of this AdresMogelijkOnjuist.  # noqa: E501
        :type: bool
        """

        self._korte_naam = korte_naam

    @property
    def straat(self):
        """Gets the straat of this AdresMogelijkOnjuist.  # noqa: E501


        :return: The straat of this AdresMogelijkOnjuist.  # noqa: E501
        :rtype: bool
        """
        return self._straat

    @straat.setter
    def straat(self, straat):
        """Sets the straat of this AdresMogelijkOnjuist.


        :param straat: The straat of this AdresMogelijkOnjuist.  # noqa: E501
        :type: bool
        """

        self._straat = straat

    @property
    def huisnummer(self):
        """Gets the huisnummer of this AdresMogelijkOnjuist.  # noqa: E501


        :return: The huisnummer of this AdresMogelijkOnjuist.  # noqa: E501
        :rtype: bool
        """
        return self._huisnummer

    @huisnummer.setter
    def huisnummer(self, huisnummer):
        """Sets the huisnummer of this AdresMogelijkOnjuist.


        :param huisnummer: The huisnummer of this AdresMogelijkOnjuist.  # noqa: E501
        :type: bool
        """

        self._huisnummer = huisnummer

    @property
    def huisletter(self):
        """Gets the huisletter of this AdresMogelijkOnjuist.  # noqa: E501


        :return: The huisletter of this AdresMogelijkOnjuist.  # noqa: E501
        :rtype: bool
        """
        return self._huisletter

    @huisletter.setter
    def huisletter(self, huisletter):
        """Sets the huisletter of this AdresMogelijkOnjuist.


        :param huisletter: The huisletter of this AdresMogelijkOnjuist.  # noqa: E501
        :type: bool
        """

        self._huisletter = huisletter

    @property
    def huisnummertoevoeging(self):
        """Gets the huisnummertoevoeging of this AdresMogelijkOnjuist.  # noqa: E501


        :return: The huisnummertoevoeging of this AdresMogelijkOnjuist.  # noqa: E501
        :rtype: bool
        """
        return self._huisnummertoevoeging

    @huisnummertoevoeging.setter
    def huisnummertoevoeging(self, huisnummertoevoeging):
        """Sets the huisnummertoevoeging of this AdresMogelijkOnjuist.


        :param huisnummertoevoeging: The huisnummertoevoeging of this AdresMogelijkOnjuist.  # noqa: E501
        :type: bool
        """

        self._huisnummertoevoeging = huisnummertoevoeging

    @property
    def postcode(self):
        """Gets the postcode of this AdresMogelijkOnjuist.  # noqa: E501


        :return: The postcode of this AdresMogelijkOnjuist.  # noqa: E501
        :rtype: bool
        """
        return self._postcode

    @postcode.setter
    def postcode(self, postcode):
        """Sets the postcode of this AdresMogelijkOnjuist.


        :param postcode: The postcode of this AdresMogelijkOnjuist.  # noqa: E501
        :type: bool
        """

        self._postcode = postcode

    @property
    def woonplaats(self):
        """Gets the woonplaats of this AdresMogelijkOnjuist.  # noqa: E501


        :return: The woonplaats of this AdresMogelijkOnjuist.  # noqa: E501
        :rtype: bool
        """
        return self._woonplaats

    @woonplaats.setter
    def woonplaats(self, woonplaats):
        """Sets the woonplaats of this AdresMogelijkOnjuist.


        :param woonplaats: The woonplaats of this AdresMogelijkOnjuist.  # noqa: E501
        :type: bool
        """

        self._woonplaats = woonplaats

    @property
    def nummeraanduiding_identificatie(self):
        """Gets the nummeraanduiding_identificatie of this AdresMogelijkOnjuist.  # noqa: E501


        :return: The nummeraanduiding_identificatie of this AdresMogelijkOnjuist.  # noqa: E501
        :rtype: bool
        """
        return self._nummeraanduiding_identificatie

    @nummeraanduiding_identificatie.setter
    def nummeraanduiding_identificatie(self, nummeraanduiding_identificatie):
        """Sets the nummeraanduiding_identificatie of this AdresMogelijkOnjuist.


        :param nummeraanduiding_identificatie: The nummeraanduiding_identificatie of this AdresMogelijkOnjuist.  # noqa: E501
        :type: bool
        """

        self._nummeraanduiding_identificatie = nummeraanduiding_identificatie

    @property
    def openbare_ruimte_identificatie(self):
        """Gets the openbare_ruimte_identificatie of this AdresMogelijkOnjuist.  # noqa: E501


        :return: The openbare_ruimte_identificatie of this AdresMogelijkOnjuist.  # noqa: E501
        :rtype: bool
        """
        return self._openbare_ruimte_identificatie

    @openbare_ruimte_identificatie.setter
    def openbare_ruimte_identificatie(self, openbare_ruimte_identificatie):
        """Sets the openbare_ruimte_identificatie of this AdresMogelijkOnjuist.


        :param openbare_ruimte_identificatie: The openbare_ruimte_identificatie of this AdresMogelijkOnjuist.  # noqa: E501
        :type: bool
        """

        self._openbare_ruimte_identificatie = openbare_ruimte_identificatie

    @property
    def woonplaats_identificatie(self):
        """Gets the woonplaats_identificatie of this AdresMogelijkOnjuist.  # noqa: E501


        :return: The woonplaats_identificatie of this AdresMogelijkOnjuist.  # noqa: E501
        :rtype: bool
        """
        return self._woonplaats_identificatie

    @woonplaats_identificatie.setter
    def woonplaats_identificatie(self, woonplaats_identificatie):
        """Sets the woonplaats_identificatie of this AdresMogelijkOnjuist.


        :param woonplaats_identificatie: The woonplaats_identificatie of this AdresMogelijkOnjuist.  # noqa: E501
        :type: bool
        """

        self._woonplaats_identificatie = woonplaats_identificatie

    @property
    def toelichting(self):
        """Gets the toelichting of this AdresMogelijkOnjuist.  # noqa: E501


        :return: The toelichting of this AdresMogelijkOnjuist.  # noqa: E501
        :rtype: list[str]
        """
        return self._toelichting

    @toelichting.setter
    def toelichting(self, toelichting):
        """Sets the toelichting of this AdresMogelijkOnjuist.


        :param toelichting: The toelichting of this AdresMogelijkOnjuist.  # noqa: E501
        :type: list[str]
        """

        self._toelichting = toelichting

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdresMogelijkOnjuist):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AdresMogelijkOnjuist):
            return True

        return self.to_dict() != other.to_dict()
