/*
 * Huidige bevragingen API
 * Deze API levert actuele gegevens over adressen, adresseerbare objecten en panden. Actueel betekent in deze API `zonder eindstatus`. De bron voor deze API is de basisregistratie adressen en gebouwen (BAG).
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: bag@kadaster.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AdresseerbaarObjectHal;

/**
 * AdresseerbaarobjectHalCollectieEmbedded
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-07-13T10:42:05.060374Z[Etc/UTC]")
public class AdresseerbaarobjectHalCollectieEmbedded {
  public static final String SERIALIZED_NAME_ADRESSEERBARE_OBJECTEN = "adresseerbareObjecten";
  @SerializedName(SERIALIZED_NAME_ADRESSEERBARE_OBJECTEN)
  private List<AdresseerbaarObjectHal> adresseerbareObjecten = null;


  public AdresseerbaarobjectHalCollectieEmbedded adresseerbareObjecten(List<AdresseerbaarObjectHal> adresseerbareObjecten) {
    
    this.adresseerbareObjecten = adresseerbareObjecten;
    return this;
  }

  public AdresseerbaarobjectHalCollectieEmbedded addAdresseerbareObjectenItem(AdresseerbaarObjectHal adresseerbareObjectenItem) {
    if (this.adresseerbareObjecten == null) {
      this.adresseerbareObjecten = new ArrayList<>();
    }
    this.adresseerbareObjecten.add(adresseerbareObjectenItem);
    return this;
  }

   /**
   * Get adresseerbareObjecten
   * @return adresseerbareObjecten
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<AdresseerbaarObjectHal> getAdresseerbareObjecten() {
    return adresseerbareObjecten;
  }


  public void setAdresseerbareObjecten(List<AdresseerbaarObjectHal> adresseerbareObjecten) {
    this.adresseerbareObjecten = adresseerbareObjecten;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdresseerbaarobjectHalCollectieEmbedded adresseerbaarobjectHalCollectieEmbedded = (AdresseerbaarobjectHalCollectieEmbedded) o;
    return Objects.equals(this.adresseerbareObjecten, adresseerbaarobjectHalCollectieEmbedded.adresseerbareObjecten);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adresseerbareObjecten);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdresseerbaarobjectHalCollectieEmbedded {\n");
    sb.append("    adresseerbareObjecten: ").append(toIndentedString(adresseerbareObjecten)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

