/* 
 * Huidige bevragingen API
 *
 * Deze API levert actuele gegevens over adressen, adresseerbaar objecten en panden. Actueel betekent in deze API `zonder eindstatus`. De bron voor deze API is de basisregistratie adressen en gebouwen (BAG).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: bag@kadaster.nl
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Een codering van de verschillende waarden die de status van een pand kan aannemen.
    /// </summary>
    /// <value>Een codering van de verschillende waarden die de status van een pand kan aannemen.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum StatusPandEnum
    {
        /// <summary>
        /// Enum Bouwvergunningverleend for value: Bouwvergunning verleend
        /// </summary>
        [EnumMember(Value = "Bouwvergunning verleend")]
        Bouwvergunningverleend = 1,

        /// <summary>
        /// Enum Bouwgestart for value: Bouw gestart
        /// </summary>
        [EnumMember(Value = "Bouw gestart")]
        Bouwgestart = 2,

        /// <summary>
        /// Enum Pandingebruiknietingemeten for value: Pand in gebruik (niet ingemeten)
        /// </summary>
        [EnumMember(Value = "Pand in gebruik (niet ingemeten)")]
        Pandingebruiknietingemeten = 3,

        /// <summary>
        /// Enum Pandingebruik for value: Pand in gebruik
        /// </summary>
        [EnumMember(Value = "Pand in gebruik")]
        Pandingebruik = 4,

        /// <summary>
        /// Enum Verbouwingpand for value: Verbouwing pand
        /// </summary>
        [EnumMember(Value = "Verbouwing pand")]
        Verbouwingpand = 5,

        /// <summary>
        /// Enum Sloopvergunningverleend for value: Sloopvergunning verleend
        /// </summary>
        [EnumMember(Value = "Sloopvergunning verleend")]
        Sloopvergunningverleend = 6,

        /// <summary>
        /// Enum Pandbuitengebruik for value: Pand buiten gebruik
        /// </summary>
        [EnumMember(Value = "Pand buiten gebruik")]
        Pandbuitengebruik = 7

    }

}
